In [1]:
from csv import reader
# Load a CSV file\n",
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
    return dataset

In [49]:
myData = load_csv("test.csv")
finalData = []
keywords = []
#print(myData)
index = 0
for i in range(1,len(myData)):
    #print(myData[i])
    #print("jfldkdjgdk")
    
    if(myData[i][1] != ""):
        finalData.append([])
        keywords.append([])
        keywords[index].append(myData[i][1])
        for j in range(2,8):
            finalData[index].append(float(myData[i][j]))
            #print(float(myData[i][j]))
            #print("hi")
        index = index+1
        
    #print("hola")
    
    if(myData[i][8] != ""):
        finalData.append([])
        keywords.append([])
        keywords[index].append(myData[i][8])
        for j in range(9,15):
            finalData[index].append(float(myData[i][j]))
            #print(float(myData[i][j]))
            #print("ei")
        index = index+1
    #print("hi")
    
    
    if(myData[i][15] != ""):
        finalData.append([])
        keywords.append([])
        keywords[index].append(myData[i][15])
        for j in range(16,22):
            finalData[index].append(float(myData[i][j]))
            #print(float(myData[i][j]))
            #print("hhh")
            
        index = index+1
    #print(finalData)
    #print("ke")
    #index = index+3
        
print(finalData)
    

[[0.0, 0.062807, 0.613317, 0.403523, 0.14975, 0.069651], [0.0, 0.062807, 0.613317, 0.403523, 0.14975, 0.069651], [0.0, 0.014305, 0.533154, 0.435281, 0.300391, 0.084629], [0.885408, 0.754565, 0.041717, 0.148915, 0.056287, 0.018326], [-0.765267, 0.922149, 0.003533, 0.003949, 0.009105, 0.015471], [0.885408, 0.754565, 0.041717, 0.148915, 0.056287, 0.018326], [0.304521, 0.237783, 0.23256, 0.281337, 0.295743, 0.09154], [0.0, 0.819863, 0.045577, 0.043173, 0.084241, 0.013035], [0.0, 0.819863, 0.045577, 0.043173, 0.084241, 0.013035], [0.563982, 0.812554, 0.058504, 0.018286, 0.064057, 0.010519], [-0.535578, 0.03907, 0.067851, 0.007087, 0.20586, 0.056956], [-0.301409, 0.245532, 0.157261, 0.056157, 0.240727, 0.272349], [-0.840877, 0.014617, 0.245873, 0.369675, 0.503655, 0.246475], [0.0, 0.08096, 0.180887, 0.451183, 0.42444, 0.138198], [0.0, 0.08096, 0.180887, 0.451183, 0.42444, 0.138198], [-0.781369, 0.020603, 0.367652, 0.467115, 0.45426, 0.02087], [-0.724291, 0.041608, 0.263313, 0.340975, 0.52762

In [55]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
from sklearn.cluster import KMeans
from collections import Counter
from mpl_toolkits.mplot3d import Axes3D
from pylab import *
from matplotlib.backends.backend_pdf import PdfPages

# pp = PdfPages('test.pdf')

# data = load_csv("./csv/female_talkshow_rgb.csv")
# #data = eval(data)
# myData = []
# for i in range(0,len(data)):
#     #print(data[i])
#     try:
#         r = eval(data[i][0])
#         g = eval(data[i][1])
#         b = eval(data[i][2])
#         myData.append([])
#         myData[i].append(r)
#         myData[i].append(g)
#         myData[i].append(b)
#     except:
#         continue
        
# #print(myData)    
    
X = np.array(finalData)


cluster_num = 10

kmeans = KMeans(n_clusters=cluster_num)
kmeans.fit(X)

centroids = kmeans.cluster_centers_
labels = kmeans.labels_

# print "centroids : "
# print centroids
# print "labels : "
# print labels

#colors = ["g.","r.","c.","y."]

#color = np.random.rand(cluster_num)

#color = ["g", "#FF0000"]
#center = ["#000000"]

c = Counter(labels)


#fig = figure(figsize=(12,8))
#ax = fig.gca(projection='3d')

clusters = []
for i in range(0,10):
    clusters.append([])
    
print(kmeans.cluster_centers_)
for i in range(len(X)):
    #print("coordinate:",X[i], "label:", labels[i], "keyword:", keywords[i])
    clusters[labels[i]].append(keywords[i])
    
for i in range(0,10):
    print(clusters[i])
    print("******")
# #     print "i : ",i
# #     print "color[labels[i]] : ",color[labels[i]]
#     ax.scatter(X[i][0], X[i][1], X[i][2], c=color[labels[i]])

# 
# for cluster_number in range(cluster_num):
#   print("Cluster {} contains {} samples".format(cluster_number, c[cluster_number]))

# ax.scatter(centroids[:, 0],centroids[:, 1], centroids[:, 2], marker = "x", s=150, linewidths = 500, zorder = 100, c=center)
#ax.scatter(centroids[:, 0],centroids[:, 1], centroids[:, 2], marker = "x", s=150, linewidths = 5, zorder = 100)
#pp.savefig()
#pp.close()
#plt.show()

[[ 0.02077489  0.19473344  0.11753392  0.12870308  0.23378099  0.12728211]
 [ 0.59693717  0.79279622  0.03132793  0.0450591   0.0548613   0.03940824]
 [-0.75925764  0.38921778  0.11011281  0.12619939  0.1981955   0.08175889]
 [-0.01214953  0.6891376   0.03941471  0.0817464   0.10387287  0.03778521]
 [-0.76603174  0.04946267  0.30496024  0.34980021  0.41983279  0.13455171]
 [ 0.63504815  0.19837866  0.08658568  0.2021916   0.21054845  0.09246838]
 [-0.00964096  0.16091226  0.17332426  0.50620526  0.24566104  0.08223989]
 [ 0.7636231   0.53722715  0.06784175  0.17779792  0.11706745  0.07055947]
 [-0.41943472  0.12446309  0.12124741  0.11809488  0.29623119  0.11919459]
 [ 0.86049432  0.86521017  0.01759716  0.04463407  0.03432687  0.02810079]]
[['renowned burger chains'], ['Beef burger'], ['burgers'], ['Beef burger'], ['burgers'], ['chain shop'], ['Faltu khabar'], ['spice'], ['time'], ['outlet'], ['interiors'], ['Huge crowd'], ['burgers'], ['burger'], ['bit'], ['bigger place'], ['guys'], 